language: node_js
node_js:
 - "8"
sudo: enabled
branches:
  only:
   - master

services:
 - docker

install: cd client && yarn install && yarn test && yarn heroku && cd ..
script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t ekofe-client client 
  - docker build -t ekofe-server server
  - docker images
  - docker tag ekofe-client $DOCKER_USERNAME/ekofe-client
  - docker tag ekofe-server $DOCKER_USERNAME/ekofe-server
  - docker push $DOCKER_USERNAME/ekofe-client
  - docker push $DOCKER_USERNAME/ekofe-server
